controller_joint_names: ['', 'FRplateJnt', 'FRstArmJnt', 'FRndArmJnt', 'FLplateJnt', 'FLstArmJnt', 'FLndArmJnt', 'RRplateJnt', 'RRstArmJnt', 'RRndArmJnt', 'RLplateJnt', 'RLstArmJnt', 'RLndArmJnt', ]
