barabasz:
    # Publish all joint states -----------------------------------
    joint_state_controller:
        type: joint_state_controller/JointStateController
        publish_rate: 50

    # The name of the controller is recommended to have the exact same joint name, proceeded by "_position_controller"
    # Position Controllers ---------------------------------------
    front_left_leg_1_position_controller:
        type: effort_controllers/JointPositionController
        joint: FLndServoJnt
        pid: {p: 1.0, i: 1.0, d: 0.0}

    front_left_leg_2_position_controller:
        type: effort_controllers/JointPositionController
        joint: FLstArmJnt
        pid: {p: 1.0, i: 1.0, d: 0.0}

    front_left_leg_3_position_controller:
        type: effort_controllers/JointPositionController
        joint: FLndArmJnt
        pid: {p: 1.0, i: 1.0, d: 0.0}


    front_right_leg_1_position_controller:
        type: effort_controllers/JointPositionController
        joint: FRndServoJnt
        pid: {p: 1.0, i: 1.0, d: 0.0}

    front_right_leg_2_position_controller:
        type: effort_controllers/JointPositionController
        joint: FRstArmJnt
        pid: {p: 1.0, i: 1.0, d: 0.0}

    front_right_leg_3_position_controller:
        type: effort_controllers/JointPositionController
        joint: FRndArmJnt
        pid: {p: 1.0, i: 1.0, d: 0.0}


    rear_right_leg_1_position_controller:
        type: effort_controllers/JointPositionController
        joint: RRndServoJnt
        pid: {p: 1.0, i: 1.0, d: 0.0}

    rear_right_leg_2_position_controller:
        type: effort_controllers/JointPositionController
        joint: RRstArmJnt
        pid: {p: 1.0, i: 1.0, d: 0.0}

    rear_right_leg_3_position_controller:
        type: effort_controllers/JointPositionController
        joint: RRndArmJnt
        pid: {p: 1.0, i: 1.0, d: 0.0}


    rear_left_leg_1_position_controller:
        type: effort_controllers/JointPositionController
        joint: RLndServoJnt
        pid: {p: 1.0, i: 1.0, d: 0.0}

    rear_left_leg_2_position_controller:
        type: effort_controllers/JointPositionController
        joint: RLstArmJnt
        pid: {p: 1.0, i: 1.0, d: 0.0}

    rear_left_leg_3_position_controller:
        type: effort_controllers/JointPositionController
        joint: RLndArmJnt
        pid: {p: 1.0, i: 1.0, d: 0.0}
