controller_joint_names: ['', 'FRndServoJnt', 'FRstArmJnt', 'FRndArmJnt', 'FLndServoJnt', 'FLstArmJnt', 'FLndArmJnt', 'RLndServoJnt', 'RLstArmJnt', 'RLndArmJnt', 'RRndServoJnt', 'RRstArmJnt', 'RRndArmJnt', ]
